version: '3'

services:
  postgresql:
    image: postgres
    container_name: tech
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=tech
      - POSTGRES_PASSWORD=tech
      - POSTGRES_DATABASE=tech
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-tech
    ports:
      - '6379-6379'